import { ChangeEvent, useState } from 'react';
import { Link, useParams } from 'wouter';
import { useQueryClient } from '@tanstack/react-query';
import { ArrowLeft, CheckCircle2, Copy, Download, FileCheck2, FileClock, FileText, UploadCloud, X } from 'lucide-react';
import { getGetCkycRequestQueryKey, getListCkycRequestsQueryKey, getListClientsQueryKey, useGetCkycRequest, useUploadCkycResponse } from '@workspace/api-client-react';
import { PageIntro, QueryError } from '@/components/workspace-shell';

function saveFile(name: string, content: string) {
  const url = URL.createObjectURL(new Blob([content], { type: 'text/plain;charset=utf-8' }));
  const link = document.createElement('a');
  link.href = url; link.download = name; link.click(); URL.revokeObjectURL(url);
}
function formatDate(value: string) { return new Intl.DateTimeFormat('en-IN', { day: '2-digit', month: 'long', year: 'numeric', hour: '2-digit', minute: '2-digit' }).format(new Date(value)); }

export default function RequestDetail() {
  const params = useParams<{ id: string }>();
  const id = Number(params.id);
  const query = useGetCkycRequest(id, { query: { enabled: Number.isFinite(id), queryKey: getGetCkycRequestQueryKey(id) } });
  const upload = useUploadCkycResponse();
  const queryClient = useQueryClient();
  const [uploadOpen, setUploadOpen] = useState(false);
  const [fileName, setFileName] = useState('');
  const [content, setContent] = useState('');
  const [feedback, setFeedback] = useState('');
  const request = query.data;
  const chooseFile = (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; setFileName(file.name); const reader = new FileReader(); reader.onload = () => setContent(String(reader.result ?? '')); reader.readAsText(file); };
  const submitUpload = () => { if (!content || !fileName) { setFeedback('Choose a response file first.'); return; } upload.mutate({ id, data: { fileName, content } }, { onSuccess: () => { setFeedback('Response uploaded. Client CKYC IDs and errors are now updated.'); setUploadOpen(false); query.refetch(); void queryClient.invalidateQueries({ queryKey: getListClientsQueryKey() }); }, onError: () => setFeedback('The response could not be processed. Check the CKYC response format and retry.') }); };

  if (query.isLoading) return <div className="animate-pulse"><div className="h-5 w-24 rounded bg-muted" /><div className="mt-6 h-10 w-2/3 rounded bg-muted" /><div className="mt-8 h-64 rounded-xl bg-card" /></div>;
  if (query.isError || !request) return <QueryError onRetry={() => query.refetch()} />;

  return <div className="animate-fade"><Link href="/requests" className="mb-6 inline-flex items-center gap-2 font-mono-ui text-[10px] uppercase tracking-[.12em] text-muted-foreground hover:text-primary" data-testid="link-back-requests"><ArrowLeft size={14} /> All requests</Link><PageIntro eyebrow="Request detail" title={request.fileName} description={`Created ${formatDate(request.createdAt)} · ${request.recordCount} records in the outbound search file.`} action={<div className="flex flex-wrap gap-2">{request.content && <button onClick={() => saveFile(request.fileName, request.content)} className="inline-flex items-center gap-2 rounded-lg border border-border bg-card px-3.5 py-2.5 text-[12px] font-bold text-foreground hover:bg-secondary" data-testid="button-download-request"><Download size={14} /> Download request</button>}<button onClick={() => setUploadOpen((open) => !open)} className="inline-flex items-center gap-2 rounded-lg bg-primary px-3.5 py-2.5 text-[12px] font-bold text-primary-foreground hover:-translate-y-0.5" data-testid="button-toggle-response-upload"><UploadCloud size={14} /> {request.status === 'response_uploaded' ? 'Replace response' : 'Upload response'}</button></div>} />
    <div className="grid gap-6 xl:grid-cols-[1fr_340px]"><div className="space-y-6"><div className="overflow-hidden rounded-xl border border-border bg-card shadow-xs"><div className="flex items-center justify-between border-b border-border px-5 py-4"><div><h3 className="font-display text-[17px] font-bold">Outbound search file</h3><p className="mt-1 text-[11px] text-muted-foreground">The exact content sent for this request</p></div><span className="flex items-center gap-1.5 font-mono-ui text-[10px] text-[#31734d]"><CheckCircle2 size={14} /> Preserved</span></div><pre className="max-h-[360px] overflow-auto bg-[#17343a] p-5 font-mono-ui text-[10px] leading-5 text-[#c2e3d9]" data-testid="text-request-content">{request.content || 'No file content available.'}</pre></div>{request.responseContent && <div className="overflow-hidden rounded-xl border border-border bg-card shadow-xs"><div className="flex items-center justify-between border-b border-border px-5 py-4"><div><h3 className="font-display text-[17px] font-bold">Response file</h3><p className="mt-1 text-[11px] text-muted-foreground">{request.responseFileName}</p></div><button onClick={() => saveFile(request.responseFileName ?? 'ckyc-response.txt', request.responseContent ?? '')} className="inline-flex items-center gap-1.5 text-[11px] font-bold text-primary hover:underline" data-testid="button-download-response"><Download size={14} /> Download</button></div><pre className="max-h-[360px] overflow-auto bg-[#17343a] p-5 font-mono-ui text-[10px] leading-5 text-[#c2e3d9]" data-testid="text-response-content">{request.responseContent}</pre></div>}</div>
      <div className="space-y-4"><div className="rounded-xl border border-border bg-card p-5 shadow-xs"><p className="font-mono-ui text-[9px] uppercase tracking-[.17em] text-muted-foreground">Trail status</p><div className="mt-5 flex items-start gap-3"><span className={`grid size-9 place-items-center rounded-lg ${request.status === 'response_uploaded' ? 'bg-[#e2f2e9] text-[#31734d]' : 'bg-[#fff1d6] text-[#9b6915]'}`}>{request.status === 'response_uploaded' ? <FileCheck2 size={17} /> : <FileClock size={17} />}</span><div><p className="text-[13px] font-bold">{request.status === 'response_uploaded' ? 'Response received' : 'Awaiting response'}</p><p className="mt-1 text-[11px] leading-5 text-muted-foreground">{request.status === 'response_uploaded' ? `Matched file: ${request.responseFileName}` : 'Upload the CKYC gateway response to close the loop.'}</p></div></div><div className="mt-5 border-t border-border pt-4"><div className="flex justify-between text-[11px]"><span className="text-muted-foreground">Records</span><span className="font-mono-ui font-medium">{request.recordCount}</span></div><div className="mt-3 flex justify-between text-[11px]"><span className="text-muted-foreground">Request ID</span><span className="font-mono-ui font-medium">#{String(request.id).padStart(5, '0')}</span></div></div></div>
        {feedback && <div className={`rounded-lg border px-4 py-3 text-[11px] ${feedback.includes('could') || feedback.includes('Choose') ? 'border-destructive/25 bg-destructive/5 text-destructive' : 'border-[#a9d8bf] bg-[#eff8f5] text-[#31734d]'}`} data-testid="status-upload">{feedback}</div>}
        {uploadOpen && <div className="rounded-xl border border-primary/25 bg-card p-5 shadow-xs animate-rise"><div className="flex items-start justify-between"><div><p className="font-mono-ui text-[9px] uppercase tracking-[.16em] text-primary">Response handoff</p><h3 className="mt-1 font-display text-[17px] font-bold">Upload gateway response</h3></div><button onClick={() => setUploadOpen(false)} aria-label="Close response upload" className="text-muted-foreground" data-testid="button-close-response-upload"><X size={16} /></button></div><label className="mt-4 flex cursor-pointer items-center gap-3 rounded-lg border border-dashed border-primary/35 bg-secondary/35 px-3 py-3 hover:border-primary" data-testid="input-response-file"><FileText size={17} className="text-primary" /><span className="min-w-0 flex-1 truncate text-[11px] font-semibold">{fileName || 'Select response file'}</span><input type="file" className="sr-only" onChange={chooseFile} data-testid="file-input-response" /></label><button onClick={submitUpload} disabled={upload.isPending} className="mt-3 flex h-9 w-full items-center justify-center gap-2 rounded-lg bg-primary text-[11px] font-bold text-primary-foreground disabled:opacity-50" data-testid="button-submit-response">{upload.isPending ? 'Uploading…' : <><UploadCloud size={14} /> Save response</>}</button></div>}</div></div>
  </div>;
}
